---
- name: Install vim
  become: yes
  ansible.builtin.apt:
    name: vim
    state: present

- name: Copy vimrc
  become_user: "{{ env_user }}"
  ansible.builtin.copy:
    src: "vim/.vimrc"
    dest: "~/.vimrc"
