---
- name: Pull docker-install repository
  ansible.builtin.git:
    update: yes
    repo: https://github.com/docker/docker-install.git
    dest: "/tmp/docker-install"

- name: Check whether docker is installed
  ansible.builtin.stat:
    path: "/usr/bin/dockerd"
  register: result

- name: Install docker via docker-install script if not installed
  become: true
  when: not result.stat.exists
  ansible.builtin.shell: "sh /tmp/docker-install/install.sh"

- name: Add env user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ env_user }}"
    append: yes
    groups:
    - docker

- name: Start docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    daemon_reload: yes
    enabled: yes
    state: started

- name: Clean up
  ansible.builtin.file:
    path: /tmp/docker-install
    state: absent
